### ISSUE TITLE
学长这个是不是你硕士毕业论文的源码？

### ISSUE THREAD

**Issue by ynuwm** [candlewill/Thesis_experiment#1]

**Comment by candlewill** [comment]
差不多，好久没更新了。没整理好。

**Comment by ynuwm** [comment]
学长，问下这个数据集CVAT原始数据里面两个值一个V，一个A。然后CVAT2.0 有四个值，最后面多出来的两个是什么？

**Comment by ynuwm** [comment]
还有个小问题cnn.py里面定义了CNN函数，别的地方好像没用到，是不是代码不全。输入（text，v，a），我想知道CNN和RMV是怎样预测V，A这两个值的。是不是最后面CNN激活函数是linear，预测的值就是v活着a的值？

**Comment by candlewill** [comment]
不好意思，好久我也没看这个了。这些问题先发我[邮箱](yunchaohe@gmail.com)吧，顺便也介绍下您，从头像上我看不出您是哪位。
